[project]
name = "cookiecrumbler-tools"
version = "0.1.0"
description = "Cookiecrumbler tools"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pygithub~=2.6.0",
    "requests~=2.32",
    "tenacity~=9.1.2",
]
